{
 "title": "AIALGO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Response Time (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top 10 Recommended Movies (Last Hour)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by(movie) (movie_recommendations_total))",
     "legendFormat": "Movie: {{movie}}"
    }
   ]
  },
  {
   "title": "Active movie recommendations from different users",
   "type": "gauge",
   "description": "Active movie recommendations from different users in the last hour",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(recommendation_requests_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}